CREATE TABLE IF NOT EXISTS pitch (
	atbat_id INT,
	ax FLOAT,
	ay FLOAT,
	az FLOAT,
	break_angle FLOAT,
	break_length FLOAT,
	break_y FLOAT,
	des TEXT(65536),
	end_speed FLOAT,
	gid VARCHAR(255),
	id INT,
	nasty INT,
	pfx_x FLOAT,
	pfx_z FLOAT,
	pitch_type VARCHAR(255),
	px FLOAT,
	pz FLOAT,
	spin_dir FLOAT,
	spin_rate FLOAT,
	start_speed FLOAT,
	sz_bot FLOAT,
	sz_top FLOAT,
	tfs INT,
	type VARCHAR(255),
	type_confidence FLOAT,
	vx0 FLOAT,
	vy0 FLOAT,
	vz0 FLOAT,
	x FLOAT,
	x0 FLOAT,
	y FLOAT,
	y0 FLOAT,
	z0 FLOAT,
	zone INT,
	PRIMARY KEY ( gid, id )
);
